version: '3'

services:
  api:
    container_name: backend-bmg-api
    image: backend-bmg-api
    build: .
    command: gunicorn app:app --bind 0.0.0.0:5005
    env_file:
      - .env
    ports:
      - "5005:5005"
    # environment:
    #   - DATABASE_URL=postgresql://jxbatqylfrecor:86178c55586376122b6cb21ba60094724b419b74f33ed8a45e35d6048161940a@ec2-54-157-16-196.compute-1.amazonaws.com:5432/d7vn051bb1qcg6
    # depends_on:
    #   - db
  
  redis:
    image: redis
    container_name: redis-container-bmg
    ports:
      - "6379:6379"

#   db:
#     container_name: db-container-bmg
#     image: postgres:12
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=pg_backend
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: {}
